---
repositories:
  - name: "dockerhub"
    url: "http://dockerhub.com"
    credential: "cred1"
    tlsverify: true

  - name: nexus1
    url: "http://nexus.io"
    credential: cred2

  - name: nexus2
    url: "http://quay.io"
    credential: cred1

  - name: nexus3
    policyPath: policies.conf
    registriesDirPath: registry
    registriesConfPath: registry/registries.conf
    tmpDir: /tmp
    cfgFile: repo.conf
    commandTimeout: 100

reportsources:
    - name: wiz
      url: "http://wiz.io"
      credential: cred1
      parameters: "a=b&c=d"
      path: "/report"
      payload: "@query.graphql"
      headers: { "Content-Type": "application/json", "TTL": 3600}

credentials:
    - name: cred1
      type: vault
      data: { "auth_url": "http://vau", "role_name": "blah", "role_type":"aws", "secret_url": "https://vsu" }

    - name: cred2
      type: basic
      data: { "user": "joe", "password": "doe"}
