---
repositories:
  - name: "dockerhub"
    url: "http://dockerhub.com"
    credential: "cred1"
    tlsverify: true

  - name: nexus1
    url: "http://nexus.io"
    credential: cred2

  - name: nexus2
    url: "http://quay.io"
    credential: cred1

reportsources:
    - name: wiz
      url: "http://wiz.io"
      credential: cred1
      parameters: "a=b&c=d"
      path: "/report"
      payload: "@query.graphql"
      headers: { "Content-Type": "application/json", "TTL": 3600}

credentials:
    - name: cred1
      type: vault
      data: { "vault_auth_url": "http://vau", "vault_role": "blah", "vault_secret_url": "https://vsu", "auth_mode": "aws" }

    - name: cred2
      type: basic
      data: { "user": "joe", "password": "doe"}